(define-module (substrate user-space root loaders desktop)
  #:use-module (substrate user-space root desktop hyprland)
  #:use-module (substrate user-space root desktop hypridle)
  #:use-module (substrate user-space root desktop qutebrowser)
  #:use-module (substrate user-space root desktop quickshell)
  #:use-module (substrate user-space root desktop mako)
  #:use-module (substrate user-space root desktop wallpaper mpvpaper)
  #:use-module (substrate user-space root desktop wallpaper swww)
  #:use-module (substrate user-space root desktop hibiki)
  #:use-module (substrate user-space root desktop wayscriber)
  #:use-module (substrate user-space root desktop pyprland)
  #:use-module (substrate user-space root desktop hyprsunset)
  #:use-module (substrate user-space root desktop greetd)
  #:use-module (substrate user-space root desktop 3d blender)
  #:use-module (substrate user-space root desktop image krita)
  #:use-module (substrate user-space root desktop video mpv ffmpeg obs kdenlive gst-editing-services mlt opentimelineio xytz)
  #:use-module (substrate user-space root desktop wayland grim slurp swappy swaylock wl-clipboard wlogout cliphist grimblast)
  #:use-module (gnu packages imagemagick)
  #:use-module (gnu packages web)
  #:re-export (hyprland hypridle qutebrowser quickshell mako mpvpaper swww imagemagick jq hibiki wayscriber python-pyprland hyprsunset greetd blender krita mpv ffmpeg obs kdenlive gst-editing-services mlt opentimelineio xytz grim slurp swappy swaylock wl-clipboard wlogout cliphist grimblast)
  #:export (root-desktop-packages))

(define-public root-desktop-packages
  (list hyprland hypridle qutebrowser quickshell mako mpvpaper swww imagemagick jq hibiki wayscriber python-pyprland hyprsunset greetd blender krita mpv ffmpeg obs kdenlive gst-editing-services mlt opentimelineio xytz grim slurp swappy swaylock wl-clipboard wlogout cliphist grimblast))
