(define-module (substrate user-space root loaders desktop)
  #:use-module (substrate user-space root desktop hyprland)
  #:use-module (substrate user-space root desktop hypridle)
  #:use-module (substrate user-space root desktop qutebrowser)
  #:use-module (substrate user-space root desktop quickshell)
  #:use-module (substrate user-space root desktop mako)
  #:use-module (substrate user-space root desktop wallpaper mpvpaper)
  #:use-module (substrate user-space root desktop wallpaper swww)
  #:use-module (substrate user-space root desktop hibiki)
  #:use-module (substrate user-space root desktop wayscriber)
  #:use-module (substrate user-space root desktop pyprland)
  #:use-module (substrate user-space root desktop hyprsunset)
  #:use-module (substrate user-space root desktop greetd)
  #:use-module (substrate user-space root desktop 3d blender)
  #:use-module (substrate user-space root desktop image krita)
  #:use-module (substrate user-space root desktop video mpv)
  #:use-module (substrate user-space root desktop video ffmpeg)
  #:use-module (substrate user-space root desktop video obs)
  #:use-module (substrate user-space root desktop video kdenlive)
  #:use-module (substrate user-space root desktop video gst-editing-services)
  #:use-module (substrate user-space root desktop video mlt)
  #:use-module (substrate user-space root desktop video opentimelineio)
  #:use-module (substrate user-space root desktop video xytz)
  #:use-module (substrate user-space root desktop wayland grim)
  #:use-module (substrate user-space root desktop wayland slurp)
  #:use-module (substrate user-space root desktop wayland swappy)
  #:use-module (substrate user-space root desktop wayland swaylock)
  #:use-module (substrate user-space root desktop wayland wl-clipboard)
  #:use-module (substrate user-space root desktop wayland wlogout)
  #:use-module (substrate user-space root desktop wayland cliphist)
  #:use-module (substrate user-space root desktop wayland grimblast)
  #:use-module (gnu packages imagemagick)
  #:use-module (gnu packages web)
  #:re-export (hyprland hypridle qutebrowser quickshell mako mpvpaper swww imagemagick jq hibiki wayscriber python-pyprland hyprsunset greetd blender krita mpv ffmpeg obs kdenlive gst-editing-services mlt opentimelineio xytz grim slurp swappy swaylock wl-clipboard wlogout cliphist grimblast)
  #:export (root-desktop-packages))

(define-public root-desktop-packages
  (list hyprland hypridle qutebrowser quickshell mako mpvpaper swww imagemagick jq hibiki wayscriber python-pyprland hyprsunset greetd blender krita mpv ffmpeg obs kdenlive gst-editing-services mlt opentimelineio xytz grim slurp swappy swaylock wl-clipboard wlogout cliphist grimblast))
