(define-module (substrate user-space root loaders emacs-packages)
  #:use-module (substrate user-space root editors emacs-packages avy)
  #:use-module (substrate user-space root editors emacs-packages emacs-god-mode)
  #:use-module (substrate user-space root editors emacs-packages emacs-gptel)
  #:use-module (substrate user-space root editors emacs-packages emacs-ht)
  #:use-module (substrate user-space root editors emacs-packages emacs-leaf)
  #:use-module (substrate user-space root editors emacs-packages emacs-mcp)
  #:use-module (substrate user-space root editors emacs-packages emacs-modus-themes)
  #:use-module (substrate user-space root editors emacs-packages emacs-monkeytype)
  #:use-module (substrate user-space root editors emacs-packages emacs-multiple-cursors)
  #:use-module (substrate user-space root editors emacs-packages emacs-org-repeat-by-cron)
  #:use-module (substrate user-space root editors emacs-packages emacs-org-roam)
  #:use-module (substrate user-space root editors emacs-packages emacs-password-store)
  #:use-module (substrate user-space root editors emacs-packages emacs-posframe)
  #:use-module (substrate user-space root editors emacs-packages emacs-sops)
  #:use-module (substrate user-space root editors emacs-packages emacs-tmr)
  #:use-module (substrate user-space root editors emacs-packages fuzzy-clock)
  #:use-module (substrate user-space root editors emacs-packages geiser)
  #:use-module (substrate user-space root editors emacs-packages mcp-server-lib)
  #:use-module (substrate user-space root editors emacs-packages notebook-mode)
  #:use-module (substrate user-space root editors emacs-packages org-mcp)
  #:use-module (substrate user-space root editors emacs-packages quick-peek)
  #:use-module (substrate user-space root editors emacs-packages scrollable-quick-peek)
  #:export (root-emacs-packages))

(define-public root-emacs-packages
  (list emacs-avy emacs-god-mode emacs-gptel emacs-ht emacs-leaf emacs-mcp emacs-modus-themes emacs-monkeytype emacs-multiple-cursors emacs-org-repeat-by-cron emacs-org-roam emacs-password-store emacs-posframe emacs-sops emacs-tmr emacs-fuzzy-clock emacs-geiser emacs-mcp-server-lib emacs-notebook-mode emacs-org-mcp emacs-quick-peek emacs-scrollable-quick-peek))
